# Generated by Django 2.2.6 on 2019-10-23 06:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=imagekit.models.fields.ProcessedImageField(upload_to='media'),
        ),
    ]
